name: flashcard_desktop_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.5
  cloud_firestore: ^4.8.1
  firedart: ^0.9.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_treeview: ^1.0.7+1
  get_it: ^7.6.0
  logger: ^1.4.0
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/config/