name: flashcard_desktop_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.5
  cloud_firestore: ^4.8.1
  firedart: ^0.9.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_treeview: ^1.0.7+1
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  window_manager: ^0.3.4
  json_annotation: ^4.6.0
  sqflite_common_ffi: any
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.2.0
  logger: ^1.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/config/