// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2e3KeL9wj5Ql2peRkD1Gnnm0uAQ4JRtM',
    appId: '1:74245061858:web:4cebb286397a06f989b2bb',
    messagingSenderId: '74245061858',
    projectId: 'flashcard-app-237f4',
    authDomain: 'flashcard-app-237f4.firebaseapp.com',
    storageBucket: 'flashcard-app-237f4.appspot.com',
    measurementId: 'G-HXKD7GGGXY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Ce2Z_snk858anBJktNNIh0SWQsCLYXE',
    appId: '1:74245061858:ios:2be8d78803d6513f89b2bb',
    messagingSenderId: '74245061858',
    projectId: 'flashcard-app-237f4',
    storageBucket: 'flashcard-app-237f4.appspot.com',
    iosClientId: '74245061858-1r7kdgofs03epc7gespdjdu763d8abk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardDesktopApp.RunnerTests',
  );
}
